### ISSUE TITLE
Unexpected behavior when requesting items to an output

### ISSUE THREAD

**Issue by thoughtRock05** [zznty/CreateFactoryLogistics#8]
# Summary

Items requested from a stock keeper do not get sent into the system.

# Replication

1. Set up a chain conveyor system
2. Add storage for an item, making sure to have more than one stack of items present
3. Tune a stock link and a stock ticker to a logistics system
4. Set up the stock ticker with a stock keeper and put the stock links on packagers connected to the storage; add frogports
5. Set up an end of line frogport
6. Go to the stock keeper

# Expected Behavior

- Items are listed in the stock keeper terminal with small squarish numbers that extend beyond 64
- Items can be added to the request space and sent to the output frogport

# Actual Behavior

- Items are listed in the terminal with classic Minecraft font and stop at 64 items, labelled as one stack
- Items can be added to the request space but will NOT be pulled from storage and sent to the output frogport

**Comment by zznty** [comment]
should be fixed in 1.0.4
regarding font changes, create one does not support fluid amounts so it defaults to minecraft one for consistency

**Comment by thoughtRock05** [comment]
Just checked again, issue persists. The rendering of numbers has changed however!

**Comment by thoughtRock05** [comment]
Issue persists with 1.0.5

**Comment by zznty** [comment]
im not able to repro this. can you record video or send the world?

**Comment by thoughtRock05** [comment]
Ill get it to you this weekend. That okay?

**Comment by thoughtRock05** [comment]
Had some extra time! I recorded a whole bunch of strange behavior. Sometimes the calling works, sometimes it doesn't. Sometimes it sends the correct amount of items, sometimes it sends less, some it sends none. The fluids cannot be added to request line at all, even if the output specifically takes fluids. I'm not really sure what's happening anymore, so Ill just give you the whole video. 
[link](https://drive.google.com/file/d/1-rPv8ENeZphFK5sf0k2rWeF6i40LkQzL/view?usp=drive_link)

**Comment by zznty** [comment]
it was my oversight with scroll stuff having only visual effects, thank you for testing!
with 1.0.6 it should be fixed and fluid requests feature was also implemented in that revision

**Comment by thoughtRock05** [comment]
All functionality seems to be present! Thanks for sticking with this issue!
